baseURL: https://paso2021.netlify.app
languageCode: es-AR
title: Elecciones 2021
theme: minimal
disqusShortname: username
googleAnalytics: ''
params:
  accent: black
  author: Calin Tataru
  backgroundColor: lightblue
  description: |
    **PASO - 12 de Septiembre**
    
    **Ministerio del Interior**
    
    **Unidad de datos**
    
    
    ![](/min_interior.png)
    
  font: Encode Sans Semi Condensed
  githubUsername: '#'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fas fa-envelope
      url: mailto:me@example.com
      weight: 1
    - name: fab fa-github
      url: https://github.com/MinIntData/blog_paso_2021
      weight: 2
    - name: fab fa-twitter
      url: https://twitter.com/username/
      weight: 3
  main:
    - name: Portada
      url: /
      weight: 1
    - name: Guía
      url: /about/
      weight: 2
    - name: Resultados Totales
      url: /totales/
      weight: 3
    - name: Slope
      url: /slope/
      weight: 4
    - name: Proyección de Bancas
      url: /Proyecciones/
      weight: 5
    - name: Apatía Electoral
      url: /Apatía_Electoral/
      weight: 6
    - url: /Apatia_files/
      
