baseURL: https://paso2021.netlify.app
languageCode: es-AR
title: Elecciones 2021
theme: minimal
disqusShortname: username
googleAnalytics: "UA-106334854-2"
params:
  accent: black
  author: Calin Tataru
  backgroundColor: lightblue
  description: |
    **PASO - 12 de Septiembre**
    
    **Ministerio del Interior**
    
    **Unidad de datos**
    
    
    ![](/min_interior.png)
    
  font: Encode Sans Semi Condensed
  githubUsername: '#'
  highlight: yes
  highlightLanguages:
    - go
    - haskell
    - kotlin
    - scala
    - swift
  highlightStyle: default
  showBorder: yes
menu:
  icon:
    - name: fab fa-github
      url: https://github.com/MinIntData/blog_paso_2021
      weight: 4
  main:
    - name: Portada
      url: /
      weight: 1
    - name: Guía
      url: /about/
      weight: 2
    - name: Resultados
      url: /totales/
      weight: 3
    - name: Tendencia
      url: /Tendencia/
      weight: 4
    - name: Proyección de Bancas
      url: /Proyecciones/
      weight: 5
    - name: Apatía Electoral
      url: /Apatía_Electoral/
      weight: 6
    - name: Participación Femenina
      url: /Género/
      weight: 7
    - name: Informes Provinciales
      url: /Informes Provinciales/
      weight: 8
    - name: tendencia21
      url: /tendencia2/
      weight: 9
    # - name: Transferencias
    #   url: /Transferencias/
    #   weight: 9




