---
title: ¿Cómo usar el sitio?
---
<style type="text/css">
.main-container {
  max-width: 720px;
  margin-left: auto;
  margin-right: auto;
}
</style>



### Presentamos diferentes visualizaciones electorales:

--------------

#### -   En la pestaña **resultados** podrán observar los totales para las paso 2021, 2019, y 2017 a nivel nacional y provincial.

------------

#### -   En **tendencia** se observa la evolución del desempeño electoral del FDT y Juntos por el Cambio para las primarias 2017, 2019 y 2021 a nivel provincia.

------------

#### -    En **proyeccion de bancas** habrán dos visualizaciones: Un conteo actualizado de la distribución de bancas en ambas cámaras del Congreso según los resultados obtenidos. Y una tabla interactiva para observar la proyección de bancas por provincia.


------------

#### -    En el **mapa de apatía** se construye un "índice de apatía" a partir del nivel histórico de ausentismo y de votos no afirmativos válidos (voto blanco y votos nulos) en PASO (2011, 2013, 2015, 2017 y 2019). Los resultados se presentan a nivel provincial y a nivel departamental.

------------

#### -    En **Participación femenina** se podrá observar si mejoró la participación de las mujeres en el armado de listas, siendo éstas *las elecciones en las que la totalidad del Congreso habrá sido electo bajo la ley de paridad.*

------------

#### -    En **Informes provinciales** se visualiza para cada provincia del país, la **transferencia de votos** entre fuerzas políticas entre las paso 2019 y 2021. También se presentan **mapas interactivos** con la diferencia de votos obtenidos por el FdT respecto a 2019, desagregado a nivel departamento y circuito electoral.  
