---
title: "Tendencia"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
#depto mapa para diputadxs interactivo ####

library(tidyverse)
library(sf)
library(leaflet)
library(leaflet.extras2)
library(leaflet.extras)

#genero centroides de poligonos dptos y extraigo coords lat long.
swing_dpto <- read_sf("dif_depto_arg.geojson") %>%
  janitor::clean_names() %>%
  unique() %>% 
  #mutate(!duplicated(geometry,)) %>% 
  mutate(centroide = st_point_on_surface(geometry)) %>%
  extract(centroide, c("lon","lat"), "\\((.*), (.*)\\)", convert = TRUE)


#clasificacion y icon size
deptoneg <- swing_dpto %>%
  filter(dif_fdt < 0) %>%
  mutate(q = ifelse(dif_fdt < -20, 30,
                    ifelse(dif_fdt > -20 & dif_fdt < -10, 20,
                           ifelse(dif_fdt > -10 & dif_fdt < -5, 12,
                                  ifelse(dif_fdt > -5 & dif_fdt < -0.1, 7,
                                  "positivo"))))
         ) 


deptopos <- swing_dpto %>%
  filter(dif_fdt > 0) %>%
  mutate(q = ifelse(dif_fdt > 20, 40,
                    ifelse(dif_fdt < 20 & dif_fdt > 10, 25,
                           ifelse(dif_fdt < 10 & dif_fdt > 5, 15,
                                  ifelse(dif_fdt < 5 & dif_fdt > 0, 10,
                                  "negativo"))))
         )
```


```{r}
#etiquetas up y dwn
labpos <- sprintf(
  "<strong>%s</strong><br/>Dif FdT: %s",
  deptopos$nomdepto, deptopos$dif_fdt) %>%
  lapply(htmltools::HTML)

labneg <- sprintf(
  "<strong>%s</strong><br/>Dif FdT: %s",
  deptoneg$nomdepto, deptoneg$dif_fdt) %>%
  lapply(htmltools::HTML)


#mapa

leaflet()  %>%
  setView(lng = -66.85067, lat = -29.41105, zoom = 6) %>% 
  addProviderTiles(provider = providers$Stamen.TonerBackground, 
                   group = "Background"
                   ) %>%
  # addPolygons(data = swing_dpto$geometry, 
  #             weight = 0.2,  
  #             fillColor = "#F2F3F4",
  #             opacity = 0.1, 
  #             fillOpacity = 0.8
  #             ) %>% 
  addPolylines(data = swing_dpto$geometry, weight = 0.4, color = "black",
               highlightOptions = highlightOptions(stroke = TRUE, 
                                                   color = "black",
                                                   bringToFront = TRUE)) %>% 
  addMapkeyMarkers(data = deptoneg, lng = deptoneg$lon, lat = deptoneg$lat,
                   icon = makeMapkeyIcon(icon = "arrow_down",
                                         color = "red",
                                         iconSize = ~q,
                                         boxShadow = FALSE,
                                         background = "transparent",
                                         htmlCode = ),
                   group = "Negativo",
                   label = labneg

  ) %>%
  addMapkeyMarkers(data = deptopos, lng = deptopos$lon, lat = deptopos$lat,

                   icon = makeMapkeyIcon(icon = "arrow_up",
                                         color = "green",
                                         iconSize = ~q,
                                         boxShadow = FALSE,
                                         background = "transparent"),
                   group = "Positivo",
                   label = labpos
                   #popup = ~village
  ) %>% 
  addLayersControl(
                   overlayGroups = c("Background","Positivo", "Negativo"),
                   options = layersControlOptions(collapsed = F)) %>% 
  addFullscreenControl(position = "bottomright", pseudoFullscreen = TRUE) %>% 
  addEasyprint()

```
