---
title: "Buenos Aires"
author: ''
date: '2021-09-12'
slug: []
categories: []
tags: []
description: ''
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(tidyverse)
library(sf)
library(leaflet)
library(leaflegend)

base_pba1921 <- read_sf("data/pba_2019_2021_dpto2.geojson")
base_pba1921_circuito <- read_sf("data/pba_2019_2021_circuito_norm.geojson")

```

----------

### -  PASO 2019 vs 2021

----------

#### **Diagrama de transferencia de votos entre agrupaciones políticas y voto blanco para la Provincia de Buenos Aires**


```{=html }
<div class="flourish-embed flourish-sankey" data-src="visualisation/7254661"style = "height: 860px; width: 1050px;"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
```

---------

#### **Mapa comparativo - Nivel Partido**

#### **Diferencia de votos obtenidos por el FdT entre 2019 y 2021 por partido**

---------

```{r dpto, width= 15.5, fig.height = 6, fig.align= 'center'}
  ##MAPA por dpto
pal19fdt <- colorQuantile('Blues',
                          reverse = FALSE ,
                          domain = base_pba1921$fdt_19, 
                          n = 8)
pal21fdt <- colorQuantile('Blues',
                          reverse = FALSE ,
                          domain = base_pba1921$fdt_21, 
                          n = 8)
paldif1921 <- colorNumeric("RdYlGn",
                           reverse = FALSE,
                           domain = base_pba1921$dif_FDT)

leaflet(base_pba1921) %>%
  addProviderTiles(providers$CartoDB.DarkMatter) %>%
  addPolygons(popup = ~paste("Departamento: ", base_pba1921$nombre_seccion,
                               "</br>% FdT 2021: ", base_pba1921$fdt_21,
                               "</br>% FdT 2019: ", base_pba1921$fdt_19,
                               "</br>Diferencia %: ", base_pba1921$dif_FDT),
                fillColor = ~paldif1921(dif_FDT),
                weight = 0,
                fillOpacity = 0.9, group = "Diferencia %") %>%
  
  addLegend(title = "Diferencia %",  
            pal = paldif1921, 
            values = ~base_pba1921$dif_FDT,
            opacity = 0.8, position = "bottomleft",
            group = "Diferencia %") %>%
  
  addPolylines(color = "white", weight = 0.6) %>% 
  
  addPolygons(popup = ~paste("Departamento: ", base_pba1921$nombre_seccion,
                               "</br>% FdT 2021: ", base_pba1921$fdt_21,
                               "</br>% FdT 2019: ", base_pba1921$fdt_19,
                               "</br>Diferencia %: ", base_pba1921$dif_FDT),
                fillColor = ~pal21fdt(fdt_21),
                weight = 0,
                fillOpacity = 1, group = "Votos Fdt 2021") %>% 
  addLegend(title = "Votos Fdt 2021", 
            pal = pal21fdt, 
            values = ~base_pba1921$fdt_21,
            opacity = 0.8,
            position = "bottomleft",
            group = "Votos Fdt 2021") %>%
  
    addPolygons(popup = ~paste("Departamento: ", base_pba1921$nombre_seccion,
                               "</br>% FdT 2021: ", base_pba1921$fdt_21,
                               "</br>% FdT 2019: ", base_pba1921$fdt_19,
                               "</br>Diferencia %: ", base_pba1921$dif_FDT),
                fillColor = ~pal19fdt(fdt_19),
                weight = 0,
                fillOpacity = 1, group = "Votos Fdt 2019") %>%
  addLegend(title = "% Votos Fdt 2019", 
            pal = pal19fdt, 
            values = ~base_pba1921$fdt_19,
            opacity = 0.8,
            position = "bottomleft", 
            group = "Votos Fdt 2019") %>% 

  addLayersControl(overlayGroups =  c("Votos Fdt 2021", "Votos Fdt 2019",
                                      "Diferencia %"),
                    options = layersControlOptions(collapsed = F)) %>% 
  hideGroup(c("Votos Fdt 2021", "Votos Fdt 2019"))
```


---------

#### **Mapa comparativo - Nivel circuito electoral**


#### **Diferencia de votos obtenidos por el FdT entre 2019 y 2021 por circuito electoral**.

---------


```{r circuito, width= 15.5, fig.height = 6, fig.align= 'center'}


pal19fdt <- colorQuantile('Blues',
                          reverse = FALSE,
                          domain = base_pba1921_circuito$fdt_19,
                          n = 8)
pal21fdt <- colorQuantile('Blues',
                          reverse = FALSE,
                          domain = base_pba1921_circuito$fdt_21, 
                          n = 8)

paldif1921 <- colorNumeric("RdYlGn",
                           reverse = FALSE,
                           domain = base_pba1921_circuito$dif_FDT)

leaflet(base_pba1921_circuito) %>%
  addProviderTiles(providers$CartoDB.DarkMatter) %>%
  addPolygons(popup = ~paste("Departamento: ", base_pba1921_circuito$departamen,
                             "</br>Circuito: ", base_pba1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_pba1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_pba1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_pba1921_circuito$dif_FDT),
              fillColor = ~paldif1921(dif_FDT),
              weight = 0,
              fillOpacity = 0.9, group = "Diferencia %") %>%
  
  addLegend(title = "Diferencia %",  
            pal = paldif1921, 
            values = ~base_pba1921_circuito$dif_FDT,
            opacity = 0.8, 
            position = "bottomleft", 
            group = "Diferencia %") %>% 
  
  addPolylines(color = "white", weight = 0.6) %>%
  addPolygons(popup = ~paste("Departamento: ", base_pba1921_circuito$departamen,
                             "</br>Circuito: ", base_pba1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_pba1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_pba1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_pba1921_circuito$dif_FDT),
              fillColor = ~pal21fdt(fdt_21),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2021") %>%
  
  addLegend(title = "% Votos Fdt 2021", 
            pal = pal21fdt, 
            values = ~base_pba1921_circuito$fdt_21,
            opacity = 0.8, position = "bottomleft", 
            group = "Votos Fdt 2021") %>% 
  
  
  addPolygons(popup = ~paste("Departamento: ", base_pba1921_circuito$departamen,
                             "</br>Circuito: ", base_pba1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_pba1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_pba1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_pba1921_circuito$dif_FDT),
              fillColor = ~pal19fdt(fdt_19),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2019") %>%
  
  addLegend(title = "% Votos Fdt 2019",  
            pal = pal19fdt, 
            values = ~base_pba1921_circuito$fdt_19,
            opacity = 0.8, 
            position = "bottomleft", 
            group = "Votos Fdt 2019" ) %>% 

  addLayersControl(overlayGroups =  c("Votos Fdt 2021", "Votos Fdt 2019",
                                      "Diferencia %"),
                   options = layersControlOptions(collapsed = FALSE)) %>% 
  hideGroup(c("Votos Fdt 2021", "Votos Fdt 2019"))

```

