---
title: "Corrientes"
author: ''
date: '2021-09-21'
slug: []
categories: []
tags: []
description: ''
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(tidyverse)
library(sf)
library(leaflet)
library(leaflet.extras2)
library(leaflegend)

base_1921_dpto <- read_sf("data/base_corrientes2_2019_2021_depto.geojson")

base_1921_circuito <- read_sf("data/base_corrientes2_2019_2021_circuito.geojson")

```

----------

### -  PASO 2019 vs 2021

----------

#### **Diagrama de transferencia de votos entre agrupaciones políticas y voto blanco para la Provincia de Corrientes**

```{=html }
<div class="flourish-embed flourish-sankey" data-src="visualisation/7295043"style = "height: 720px; width: 1050px;"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
```

---------

#### **Voto al FdT y Nivel Socioeconómico**


#### -    En la provincia de Corrientes, se observa un patrón similar al de la provincia de Buenos Aires, existe una relación inversa entre nivel socioeconómico y voto al Frente de Todos (a mayor nivel socioeconómico, menor voto al FdT) .

---------

```{=html }
<div class="flourish-embed flourish-scatter" data-src="visualisation/7333325"><script src="https://public.flourish.studio/resources/embed.js"></script></div>

```

---------

#### **Voto a JxC y Nivel Socioeconómico**


#### -    La principal coalición opositora ha mejorado su desempeño electoral en circuitos de bajos ingresos en Corrientes, aunque se mantiene la relación positiva entre ingresos y mayor apoyo electoral a JxC. 
#### -    Un caso destacable es el circuito 106 del departamento Concepción, uno de los más pobres de la provincia, donde JxC saca 35 puntos porcentuales más que el Frente de Todos.


----------

```{=html }
<div class="flourish-embed flourish-scatter" data-src="visualisation/7333418"><script src="https://public.flourish.studio/resources/embed.js"></script></div>

```

---------

#### **Participación y Nivel Socioeconómico**


#### -    No se observa una clara relación entre participación electoral y nivel socioeconómico, esto indicaría que los niveles de apatía no necesariamente están relacionados con el nivel de ingresos.


----------

```{=html }
<div class="flourish-embed flourish-scatter" data-src="visualisation/7333449"><script src="https://public.flourish.studio/resources/embed.js"></script></div>

```

---------

#### **Mapa comparativo - Diferencia de votos obtenidos por el FdT entre 2019 y 2021 por departamento**.

```{r dpto, width= 16, fig.height = 7, fig.align= 'center'}
##mapa dpto


pal19fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 19:70)
pal21fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 19:60)
paldif1921 <- colorNumeric('Reds',reverse = TRUE ,domain = base_1921_dpto$dif_FDT)


leaflet(base_1921_dpto) %>%
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~paldif1921(dif_FDT),
              weight = 0,
              fillOpacity = 0.9, group = "Diferencia %") %>%

  addLegend(title = "Diferencia %",
            pal = paldif1921,
            values = ~base_1921_dpto$dif_FDT,
            opacity = 0.8,
            position = "bottomleft",
            group = "Diferencia %") %>%

  addPolylines(color = "black", weight = 0.6) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~pal21fdt(fdt_21),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2021") %>%

  addLegend(title = "Votos Fdt 2021",
            pal = pal21fdt,
            values = ~base_1921_dpto$fdt_21,
            opacity = 0.8,
            position = "bottomleft",
            group = "Votos Fdt 2021") %>%

  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~pal19fdt(fdt_19),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2019") %>%

  addLegend(title = "Votos Fdt 2019",
            pal = pal19fdt,
            values = ~base_1921_dpto$fdt_19,
            opacity = 0.8,
            position = "bottomleft",
            group = "Votos Fdt 2019") %>%

  addLayersControl(overlayGroups =  c("Votos Fdt 2021", "Votos Fdt 2019",
                                      "Diferencia %"),
                   options = layersControlOptions(collapsed = F)) %>%
  hideGroup(c("Votos Fdt 2021", "Votos Fdt 2019"))%>%
  addEasyprint(options = easyprintOptions(
                                          title = 'Imprimir Mapa',
                                          position = 'bottomright',
                                          exportOnly = TRUE))
```



---------

#### **Mapa comparativo - Diferencia de votos obtenidos por el FdT entre 2019 y 2021 por circuito**.

```{r circuito, width= 16, fig.height = 7, fig.align= 'center'}



pal19fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 0:100)
pal21fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 0:100)
paldif1921 <- colorNumeric("RdYlGn",reverse = FALSE ,domain = base_1921_circuito$dif_FDT)

leaflet(base_1921_circuito) %>%
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_circuito$depto,
                             "</br>Circuito: ", base_1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_1921_circuito$dif_FDT),
              fillColor = ~paldif1921(dif_FDT),
              weight = 0,
              fillOpacity = 0.9, group = "Diferencia %") %>%

  addLegend(title = "Diferencia %",  pal = paldif1921, values = ~base_1921_circuito$dif_FDT,
            opacity = 0.8, position = "bottomleft", group = "Diferencia %") %>%

  # addPolylines(color = "black", weight = 0.6) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_circuito$depto,
                             "</br>Circuito: ", base_1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_1921_circuito$dif_FDT),
              fillColor = ~pal21fdt(fdt_21),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2021") %>%

  addLegend(title = "% Votos Fdt 2021",  pal = pal21fdt, values = ~base_1921_circuito$fdt_21,
            opacity = 0.8, position = "bottomleft", group = "Votos Fdt 2021", ) %>%


  addPolygons(popup = ~paste("Departamento: ", base_1921_circuito$depto,
                             "</br>Circuito: ", base_1921_circuito$circuito,
                             "</br>% FdT 2021: ", base_1921_circuito$fdt_21,
                             "</br>% FdT 2019: ", base_1921_circuito$fdt_19,
                             "</br>Diferencia %: ", base_1921_circuito$dif_FDT),
              fillColor = ~pal19fdt(fdt_19),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2019") %>%

  addLegend(title = "% Votos Fdt 2019",  pal = pal19fdt, values = ~base_1921_circuito$fdt_19,
            opacity = 0.8, position = "bottomleft", group = "Votos Fdt 2019" ) %>%

  addLayersControl(overlayGroups =  c("Votos Fdt 2021", "Votos Fdt 2019",
                                      "Diferencia %"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup(c("Votos Fdt 2021", "Votos Fdt 2019"))%>%
  addEasyprint(options = easyprintOptions(
                                          title = 'Imprimir Mapa',
                                          position = 'bottomright',
                                          exportOnly = TRUE))
```

