---
title: "Formosa"
author: ''
date: '2021-09-22'
slug: []
categories: []
tags: []
description: ''
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(tidyverse)
library(sf)
library(leaflet)
library(leaflegend)

base_1921_dpto <- read_sf("data/base_formosa_2019_2021_depto.geojson")


```

----------

### -  PASO 2019 vs 2021

---------


#### **Diagrama de transferencia de votos entre agrupaciones políticas y voto blanco para la Provincia de Formosa**

 
```{=html }
<div class="flourish-embed flourish-sankey" data-src="visualisation/7408347"><script src="https://public.flourish.studio/resources/embed.js"></script></div>
```


----------


#### **Mapa comparativo - Diferencia de votos obtenidos por el FdT entre 2019 y 2021 por departamento**.

```{r dpto, width= 16, fig.height = 7, fig.align= 'center'}
##MAPAS
##dpto con 3 capas

pal19fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 30:100)
pal21fdt <- colorNumeric('Blues',reverse = FALSE ,domain = 30:100)
paldif1921 <- colorNumeric('Reds',reverse = TRUE ,domain = base_1921_dpto$dif_FDT)


leaflet(base_1921_dpto) %>%
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~paldif1921(dif_FDT),
              weight = 0,
              fillOpacity = 0.9, group = "Diferencia %") %>%

  addLegend(title = "Diferencia %",
            pal = paldif1921,
            values = ~base_1921_dpto$dif_FDT,
            opacity = 0.8,
            position = "bottomleft",
            group = "Diferencia %") %>%

  addPolylines(color = "black", weight = 0.6) %>%
  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~pal21fdt(fdt_21),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2021") %>%

  addLegend(title = "Votos Fdt 2021",
            pal = pal21fdt,
            values = ~base_1921_dpto$fdt_21,
            opacity = 0.8,
            position = "bottomleft",
            group = "Votos Fdt 2021") %>%

  addPolygons(popup = ~paste("Departamento: ", base_1921_dpto$nomdepto,
                             "</br>% FdT 2021: ", base_1921_dpto$fdt_21,
                             "</br>% FdT 2019: ", base_1921_dpto$fdt_19,
                             "</br>Diferencia %: ", base_1921_dpto$dif_FDT),
              fillColor = ~pal19fdt(fdt_19),
              weight = 0,
              fillOpacity = 1, group = "Votos Fdt 2019") %>%

  addLegend(title = "Votos Fdt 2019",
            pal = pal19fdt,
            values = ~base_1921_dpto$fdt_19,
            opacity = 0.8,
            position = "bottomleft",
            group = "Votos Fdt 2019") %>%

  addLayersControl(overlayGroups =  c("Votos Fdt 2021", "Votos Fdt 2019",
                                      "Diferencia %"),
                   options = layersControlOptions(collapsed = F)) %>%
  hideGroup(c("Votos Fdt 2021", "Votos Fdt 2019"))
```


